tud-zih-energy/lo2s

include/lo2s/util.hpp
src/config.cpp
src/util.cpp

uses
(/proc/sys/kernel/perf_event_mlock_kb * 1000 )/ pagesize -1
to calculate the correct value

Calculate the correct mmap-page value on the fly

---

include/lo2s/perf/event_reader.hpp
include/lo2s/util.hpp
src/config.cpp
src/monitor/interval_monitor.cpp
src/monitor/process_monitor.cpp
src/util.cpp

This pull request should reset the default mmap value to the previous default of 16 as well as adding
a more informative error message[citation needed] and cleaning up follow up exceptions so that the error message is more highlighted. I have made the decision to abort execution when such an error is met, as we can not recover from this
```bash
cve@archlinux ~/lo2s/build (git)-[issue-25-revert-mmap-pages] % ./lo2s -m 512 bash
[cve@archlinux build]$ bash
[cve@archlinux build]$ bash
[cve@archlinux build]$ bash
[cve@archlinux build]$ bash
[1514986765027380380][pid: 2994][tid:140135648560960][ERROR]: mapping memory for recording events failed. You can try to decrease the buffer size with the -m flag, or try to increase the amount of mappable memory by increasing …
```

Issue 25 revert mmap pages

---

include/lo2s/config.hpp
src/config.cpp
src/monitor/main_monitor.cpp

This pull requests adds code to set the creator field of the otf2 archive metadata to the used command line.

Issue 40 Add full lo2s arguments to trace archive metadata

---

include/lo2s/io.hpp
include/lo2s/perf/event_provider.hpp
include/lo2s/perf/tracepoint/format.hpp
src/config.cpp
src/perf/event_provider.cpp
src/perf/tracepoint/format.cpp

Changes:
* list available events (predefined and kernel PMU) with `--list-events`
* list available tracepoint events with `--list-tracepoints`
* show descriptive error when using `x86_adapt`-related switches but `lo2s` was built without support for `x86_adapt`.
* group options in usage section
* add `lo2s [OPTIONS] -a` as invocation pattern in usage section
* give names to arguments to options
* add usage section explaining arguments to options.

Issue #49: usability enhancements

---

include/lo2s/trace/trace.hpp
src/monitor/process_monitor.cpp
src/trace/trace.cpp

Add traced processes in a tree to the trace.
As taken from 6422a2c:
```
Suppose on machine HAL 9000, lo2s traced a process "foo" which spawned
some threads and another process "bar", the resulting system tree now
looks something like this:
<root node>
`-- <machine "HAL 9000">
`-- <process "foo">         \
|   `-- <thread 1234>       |
|   `-- ...                 |
|   `-- <thread 1337>       | new process subtree
|   `-- <process "bar">     |
|       `-- ...             /
`-- <Metric Location Group>
`-- <package 0>
`-- ...
`-- <package n>
```

Issue #5: process tree

---

include/lo2s/error.hpp
include/lo2s/perf/tracepoint/format.hpp
src/main.cpp
src/perf/tracepoint/exit_reader.cpp
src/perf/tracepoint/format.cpp
src/perf/tracepoint/metric_monitor.cpp
src/perf/tracepoint/switch_writer.cpp

Previously, if parsing a tracepoint event failed, an uncaught
`std::ios_base::failure` terminated `lo2s`.
Now, a `lo2s::perf::tracepoint::EventFormat::ParseError` is thrown. Alongside,
possible causes for parsing failure are logged, such as missing permissions on
/sys/kernel/debug or a non-existent event.
If parsing fails when opening the tracepoint `SwitchWriter`/`ExitReader`, log
accordingly and die with an (hopefully helpful) error message.  If parsing fails
when opening regular tracepoint events (with `-t`), log and ignore the event.
If the changes are approved of, I'd like to sqash and remove all the typos from
the commit messages.

Issue 52: Uncaught I/O-exception

---

include/lo2s/trace/trace.hpp
src/trace/trace.cpp

This pull request splits up the current locations_ map into 4 different location containers, to ensure uniqueness of the writer and locations where it applies. (For information on which writer/locations are unique and which not, see the comments above the metric_writer, sample_writer and cpu_writer functions inside src/trace/trace.cpp)

Issue 63 Split up locations to make the creation of writers semantically correct

---

CMakeLists.txt
include/lo2s/config.hpp
include/lo2s/metric/x86_energy/metrics.hpp
include/lo2s/metric/x86_energy/monitor.hpp
include/lo2s/monitor/main_monitor.hpp
include/lo2s/trace/trace.hpp
src/config.cpp
src/metric/x86_energy/metrics.cpp
src/metric/x86_energy/monitor.cpp
src/monitor/main_monitor.cpp

This adds a new type of monitor, which is used to read x86_energy counters. It utilizes the system tree provided by lo2s to spawn threads and write metric events at the corresponding cpus.

Adds x86 energy metrics

---

include/lo2s/perf/counter/abstract_writer.hpp
include/lo2s/perf/counter/cpu_writer.hpp
include/lo2s/perf/counter/process_writer.hpp
include/lo2s/perf/sample/reader.hpp
include/lo2s/perf/sample/writer.hpp
include/lo2s/trace/trace.hpp
src/monitor/process_monitor.cpp
src/perf/counter/abstract_writer.cpp
src/perf/counter/process_writer.cpp
src/perf/sample/writer.cpp
src/trace/trace.cpp

The old mechanism for the cpu id metric was borked. Instead of parsing some file in proc, we actually ask perf for the correct cpu for every sample. This has the nice site effect that we can remove a virtual call.

Cpu id metric rework

---

include/lo2s/monitor/main_monitor.hpp
include/lo2s/perf/counter/cpu_writer.hpp
include/lo2s/trace/trace.hpp
src/monitor/main_monitor.cpp
src/perf/counter/process_writer.cpp
src/trace/trace.cpp

Instead, it is basically in the Trace now.
The not so nice thing right now is, that the Trace needs to know about perf or the EventCollection, but that is better than the MainMonitor is coupled with output logic. Maybe I find a different location to initialize the perf_metric_class(), but I doubt that.

Removed get_metric_class from MainMonitor

---

include/lo2s/metric/x86_adapt/monitor.hpp
include/lo2s/metric/x86_adapt/node_monitor.hpp
include/lo2s/metric/x86_energy/monitor.hpp
include/lo2s/perf/counter/abstract_writer.hpp
include/lo2s/perf/tracepoint/writer.hpp
src/metric/plugin/channel.cpp
src/metric/x86_adapt/monitor.cpp
src/metric/x86_adapt/node_monitor.cpp
src/metric/x86_energy/monitor.cpp
src/perf/counter/abstract_writer.cpp
src/perf/counter/process_writer.cpp
src/perf/sample/writer.cpp
src/perf/tracepoint/writer.cpp

This should improve performance for writing any metric to otf2 traces

Use improved otf2xx metric event handling

---

include/lo2s/perf/tracepoint/switch_writer.hpp
include/lo2s/trace/trace.hpp
src/perf/tracepoint/switch_writer.cpp
src/trace/trace.cpp

This also updates otf2xx to the latest commit on master.
And fixes the DSO resolution bug (see #90)

Refactor switch writer to use calling_context_enter/leave

---

include/lo2s/trace/trace.hpp
src/trace/trace.cpp

Fixes #95 
If the environment variable LO2S_OUTPUT_LINK is defined, generate a symlink to the latest
trace with $LO2S_OUTPUT_LINK as its name, but only if the path does not exist or is in itself a symlink

Generate symlink to latest trace

---

CMakeLists.txt
cmake/CheckStructHasBitField.cmake
include/lo2s/monitor/cpu_switch_monitor.hpp
include/lo2s/perf/context_switch/reader.hpp
include/lo2s/perf/context_switch/writer.hpp
include/lo2s/perf/event_reader.hpp
include/lo2s/perf/tracepoint/reader.hpp
src/perf/context_switch/writer.cpp
src/perf/tracepoint/switch_writer.cpp

This fixes #79.
This PR implements recording of ContextSwitch Events using PERF_RECORD_SWITCH instead of the older tracepoint based SwitchWriter, which has the advantage of working without root privileges. 
The only remaining thing that needs root privileges in system-wide mode is the ExitReader, which we should replace shortly with a PERF_RECORD_COMM based solution similar to #84
As PERF_RECORD_SWITCH events were only introduced in Kernel 4.3, use of this feature is guarded by a cmake check and the cmake option USE_PERF_RECORD_SWITCH

Adds perf record switch support

---

include/lo2s/line_info.hpp
include/lo2s/mmap.hpp
src/bfd_resolve.cpp
src/mmap.cpp
src/trace/trace.cpp

This fixes #102. I'm partial to calling these functions "unresolvable" instead of "unknown". 
----
The source code locations generated for instruction pointers which lie
unresolvable functions are now less cluttered.  Instead of generating
LineInfos (which will later be turned into SCLs and function regions)
that contain the IP, they are now melded together if IP resolution
failed in similar ways:
* IP does not lie in range of a memory map known to lo2s?  LineInfo for
IP becomes "\<unmapped function\>", located in DSO "\<unknown binary\>".
* IP lies in range of a mapped DSO, but function name resolution fails
(e.g. for stripped binaries)? LineInfo becomes "\<unknown function\>",
located in the given DSO.
Including the IP when naming SCLs and function regions only introduces
visual clutter …

Improve LineInfo for IPs in unresolvable functions

---

include/lo2s/monitor/process_monitor.hpp
include/lo2s/perf/sample/writer.hpp
include/lo2s/perf/tracepoint/switch_writer.hpp
include/lo2s/trace/trace.hpp
src/monitor/process_monitor.cpp
src/perf/sample/writer.cpp
src/perf/tracepoint/switch_writer.cpp
src/trace/trace.cpp

This fixes #112 
This PR adds thread nodes to the calling context tree which serve as parents to the calling context nodes, which previously were directly attached to the trees root
This also fixes an issue in call graph mode (-g) where the calling context reference number was not increased when inner calling context nodes where inserted
[trace_cctx.zip](https://cloudstore.zih.tu-dresden.de/index.php/s/jnoAqmOWoih9r3h) contains a small example trace showcasing the new feature.

Issue 112 incorrect calling context

---

include/lo2s/config.hpp
include/lo2s/perf/sample/reader.hpp
include/lo2s/time/time.hpp
man/lo2s.1.pod
src/config.cpp

Add a special "pebs" clock, which will give the same timestamps as "monotonic-raw", but is set up in a slightly different way to support the large PEBS feature of newer (Skylake+) Intel processors

Add a special "pebs" clockid

---

man/lo2s.1.pod
src/config.cpp

To more reflect the fact that readout-interval is now just somewhat of
an upper bound on readout intervals

Update readout interval documentation

---

man/lo2s.1.pod
src/config.cpp
src/perf/event_provider.cpp

This PR is still somewhat of a request for comments
Time interval based metric recording (TIBMR) is the new default
`--metric-frequency` controls the frequency in TIBMR
Event count based metric recording (ECBMR) is now only used if a `--metric-leader`
is given
`--metric-count` controls the number of events that have to elapse in
ECBMR
`--metric-frequency` can only be used in TIBMR
`--metric-count` can only be used with a `--metric-leader` in ECBMR
Both can  be ommitted as both have default values
When cpu-clock isn't available we try to fallback to the old default metric leaders and print a warning
This fixes #121

Introduce time interval based metric recording

---

.travis.yml
include/lo2s/io.hpp
include/lo2s/metric/x86_adapt/knobs.hpp
lib/x86_adapt/include/x86_adapt_cxx/configuration_items.hpp
src/config.cpp

With this PR, CPU x86_adapt events are only listed if they aren't available as a node event, furthermore print a description for every event
This fixes #125

List x86_adapt cpu knobs only if they are not node knobs, also print description

---

include/lo2s/perf/sample/reader.hpp
src/monitor/thread_monitor.cpp

for #137 
close stop pipe when ThreadMonitor is stopped
close fd of perf::sample::Reader early

early FD cleanup

---

include/lo2s/perf/event_reader.hpp
include/lo2s/perf/sample/reader.hpp
include/lo2s/perf/sample/writer.hpp
include/lo2s/trace/trace.hpp
src/perf/sample/writer.cpp
src/trace/trace.cpp

This results in a more accurate depiction of when which process was active
This Fixes #135

Also write Calling Context Enter/Leaves in process_mode

---

include/lo2s/topology.hpp
src/config.cpp
src/topology.cpp

When running in a virtual-environment, switch the default sampling event to `cpu-clock`
Fixes #141

Adds a check if running hyporvised and adapt sampling event

---

.gitmodules
include/lo2s/trace/reg_keys.hpp
include/lo2s/trace/trace.hpp
src/metric/x86_adapt/metrics.cpp
src/metric/x86_energy/metrics.cpp
src/monitor/cpu_set_monitor.cpp
src/monitor/tracepoint_monitor.cpp
src/perf/sample/writer.cpp
src/trace/trace.cpp

This PR bases the functionality of the trace.cpp on the otf2::definition::registry container instead of
using a zoo of home grown std::map()'s.
This might still contain outstanding issues, due to how long this has been in the works but the test traces i did for system and  process mode look normal to me, so I think this is ready for consideration.
This fixes #124

Issue 124 trace cpp with registry

---

.gitmodules
CMakeLists.txt
include/lo2s/bfd_resolve.hpp
include/lo2s/monitor/threaded_monitor.hpp
include/lo2s/perf/tracepoint/reader.hpp
include/lo2s/topology.hpp
include/lo2s/trace/trace.hpp
src/mmap.cpp
src/monitor/threaded_monitor.cpp
src/perf/tracepoint/writer.cpp
src/trace/trace.cpp
src/util.cpp

Part 1 of the effort to remove boost from lo2s
This PR replaces boost::format with the venerable fmtlib, as well as removing some boost dependencies that weren't used at all.

Replace boost::format with fmtlib

---

include/lo2s/perf/counter_description.hpp
include/lo2s/perf/event_provider.hpp
src/config.cpp
src/perf/event_provider.cpp

This PR adds an indicator to the list-events switch, which shows if an event is only available in process monitoring or system mode.
I haven't tackled the "maybe also check it root privileges are needed part" but that should be easy to implement as well, as we most probably only have to check for EACCES
This PR resolves #117 
This is Also based on #144, so that should probably be merged first.

Issue 117 improve list events

---

include/lo2s/config.hpp
src/config.cpp

I think we can live with using 8 byte more memory every time we run lo2s for the sake of more consistent formatting.
This fixes #151 (At least a little)

Remove the only union from lo2s

---

include/lo2s/io.hpp
src/bfd_resolve.cpp
src/mmap.cpp
src/perf/tracepoint/format.cpp
src/trace/trace.cpp

This PR replaces the boost::algorithm string function used by lo2s with our own homegrown nitro variants
This depends on https://github.com/tud-zih-energy/lo2s/pull/154 so have a look at that first

Issue 147 Part 3 boost::algorithm removal

---

include/lo2s/monitor/abstract_process_monitor.hpp
include/lo2s/monitor/dummy_monitor.hpp
include/lo2s/monitor/process_monitor.hpp
include/lo2s/trace/trace.hpp
src/monitor/process_monitor.cpp
src/process_controller.cpp
src/trace/trace.cpp

This looks more like it:
- check for the ptrace EVENT_EXEC event as the name is already updated there
- fix update_process_name (the region.add_member thingy did not work at  all)
- also change the name of the otf2::definition::location
This fixes #143

Receive all process names

---

CMakeLists.txt

As the title says.
In the meeting last friday, @tilsche and  I decided to just require C++17 as a whole instead of the different individual language features.
@bmario should probably take a look at this, because he understands CMake probably as much as a human mind is able to.

Require C++17 as a whole instead of the individual language features

---

src/perf/event_provider.cpp

Now raw events can be shorter or longer as on perf

Changed RAW format hopefully for the better

---

include/lo2s/trace/trace.hpp
src/trace/trace.cpp

This way we dont get extraneous empty metric_classes
This fixes #167
Tested, just making a PR so that Travis and the turtle can do their work

Create cpu/perf_metric_class on demand

---

.github/workflows/cmake.yml
.gitmodules
CMakeLists.txt
README.md
include/lo2s/config.hpp
src/config.cpp
src/main.cpp
src/trace/trace.cpp

Finally, this replaces the last remaining part of Boost in lo2s using nitro::options. For now, it uses a feature branch of nitro.

Replace boost::program_options with nitro::options

---

src/trace/trace.cpp

Adds a property to the trace that shows a human readable time string of
when measuring started.
This fixes #170

feat: add LO2S::STARTING_TIME property

---

include/lo2s/trace/reg_keys.hpp
src/trace/trace.cpp
src/util.cpp

Previously every thread became it's own regions_group with the name of the thread as the name of the regions_group
Now we have one regions_group per process with the process' name.
Changing the behaviour to one regions group per executable name (=All processes with name "FIRESTARTER" share the same group)  would be trivial to implement if we would want that instead.
* Add thread->process relations to ExecutionScopeGroup in merge_ips
and get_comms_for_running_processes() too
* in ~Trace(): use ExecutionScopeGroup to get the process of threads and
then use the process' name instead of the thread name for the
regions_group
This fixes #180

 fix(trace): Set regions_group name to name of process

---

.github/workflows/cmake.yml

Support was dropped: https://github.com/actions/virtual-environments/issues/2950

Removes gcc and clang older than 9.x

---

CMakeLists.txt
include/lo2s/config.hpp
include/lo2s/measurement_scope.hpp
include/lo2s/monitor/bio_monitor.hpp
include/lo2s/monitor/main_monitor.hpp
include/lo2s/perf/bio/block_device.hpp
include/lo2s/perf/bio/event_cacher.hpp
include/lo2s/perf/bio/reader.hpp
include/lo2s/perf/bio/writer.hpp
include/lo2s/trace/reg_keys.hpp
include/lo2s/trace/trace.hpp
include/lo2s/util.hpp
man/lo2s.1.pod
src/config.cpp
src/monitor/bio_monitor.cpp
src/monitor/main_monitor.cpp
src/perf/bio/event_cacher.cpp
src/trace/trace.cpp
src/util.cpp

Introduces the --block-io switch to record block I/O events
The implementation is discussed in detail in #196 
This closes #196

feat(block I/O): Implement Block I/O tracing

---

include/lo2s/config.hpp
include/lo2s/perf/sample/reader.hpp
include/lo2s/perf/tracepoint/reader.hpp
include/lo2s/perf/util.hpp
include/lo2s/util.hpp
man/lo2s.1.pod
src/config.cpp
src/perf/counter/group/reader.cpp
src/perf/util.cpp
src/util.cpp

This adds an option to filter perf events by cgroup
@rschoene could you confirm that this does what you want it to do?
Caveats:
* This assumes that cgroupfs is mounted at /sys/fs/cgroup, where it is mounted on 99,9% of Linux systems. However there is nothing stopping you from mounting it wherever you like. Do we:
1. Live with that
2. Reguire full paths, which practically no other tool requires
3. Port perfs rather ugly cgroupfs-mountpoint searching code.
* This only covers perf events, which makes sense for now (why filter x86_energy by cgroup) but we must keep that in mind for some place in the future where not everything in lo2s comes from perf (BPF for example)
This closes #198 .

Issue 198 cgroups

---

include/lo2s/perf/counter/counter_collection.hpp
include/lo2s/perf/counter/group/writer.hpp
include/lo2s/perf/counter/userspace/writer.hpp
include/lo2s/perf/event_description.hpp
include/lo2s/trace/trace.hpp
src/perf/counter/group/writer.cpp
src/perf/counter/userspace/writer.cpp
src/perf/event_provider.cpp

This fixes #208
PMU events may come with a separate scaling factor, which needs to be
multiplied with the event read-out. This is located in [event_path].scale.
As I was touching the PMU event read code anyways I also added support
for parsing the [event_path].unit, which tells us the unit of the PMU event.
Traces look fine by me, can you further test this @s9105947 ?

fix(metrics): Use .scale and .unit for PMU events

---

include/lo2s/process_controller.hpp
src/process_controller.cpp

It hurts to exit the main loop by exception, when during the stack unwinding another exception gets thrown. We're then directly in std::terminate land and the error message is "Success".

Don't use exceptions for control flow

---

src/monitor/cpu_set_monitor.cpp
src/monitor/process_monitor.cpp
src/monitor/scope_monitor.cpp

Fixes race condition and cleanup for CPU ScopedMonitors, closes #226.
See commit messages for detailed description.
Produces errors like this:
```
[108994189964536][pid: 129226][tid: 129226][ERROR]: Failed to create/start all CPU monitors (104 out of 128 suceeded): remove already existing monitors
[108994577353307][pid: 129226][tid: 129226][FATAL]: Aborting: Too many open files
```

fix monitor cleanup and potential race condition

---

src/trace/trace.cpp

The old version used `auto&` as type for function results, and did not handle the underlying lifetime of the objects correctly resulting in undefined behavior. This is replaced by a copy (`auto`) where modification of the variable is required, and `const auto&` where it is not.
This resulted in the map of system_tree_node by package to not be initialized fully (second package was missing), from where later lookups to this map failed. This commit fixes this initialization and eliminates the previously occuring lookup error from `map::at()`.

trace registry setup: fix lifetime of variables

---

README.md
man/CMakeLists.txt

The man page build and install process now follows more sane defaults: If the requirements for building the man pages (pod2man, gzip) are available, it is built by default. Otherwise, man pages are disabled. This man page support is reported to the user as an enabled or disabled feature as part of the feature summary.
If the man page is enabled explicitly (`-DINSTALL_MANPAGE=ON`), but the dependencies are not found the configuration is aborted. This breaks previous behavior, which skipped man page generation with a warning and carried on -- even with man pages explicitly enabled.
Additionally, the man page is now compressed with gzip before being installed. This follows the requirement of the debian package maintainer manual. In order to avoid potential conflict on multiple invocations, …

fix man page install

---

include/lo2s/perf/calling_context_manager.hpp
include/lo2s/perf/sample/writer.hpp
include/lo2s/perf/tracepoint/switch_writer.hpp
include/lo2s/process_info.hpp
include/lo2s/trace/trace.hpp
src/monitor/cpu_set_monitor.cpp
src/monitor/main_monitor.cpp
src/monitor/process_monitor.cpp
src/perf/sample/writer.cpp
src/perf/time/reader.cpp
src/perf/tracepoint/switch_writer.cpp
src/trace/trace.cpp

while still destructing the monitoring threads early.
This fixes an issue with unknown functions due to missing mmap entries when deconstructing monitors of threads early.
Fixes #240

fix: move calling context merge until the very end,

---

cmake/FindBinutils.cmake

Newer binutils  (>=2.40) want to be linked against libsframe and libzstd.
To still support older binutils, we guess with this heuristic:
If we find a libsframe, we require a suitable libzstd.

build: Link with libsframe and libzstd

---

CMakeLists.txt

Some distributions (e.g. Arch Linux) do not guarantee to ship static libraries.
So change the default for lo2s_USE_STATIC_LIBS to OFF.

fix(build): Set lo2s_USE_STATIC_LIBS to OFF

---

src/metric/sensors/recorder.cpp

Apparently intermixing C strings and C++ strings is a bad idea (tm), so keep it as split as possible by using an intermediate std::vector
This fixes #258

fix(sensors): Clear names for sensors with multiple scopes

---

.github/workflows/cmake.yml
CMakeLists.txt
README.md
include/lo2s/build_config.hpp.in
include/lo2s/perf/sample/reader.hpp
src/config.cpp
src/perf/util.cpp

use_clockid is present since Linux 4.1 and allows for finer grained control over the used perf clock.
All observed systems, like ZIH's Taurus and DKRZ' Levante, have support for use_clockid, so we can safely remove this codepath.

feat(sampling): Remove support for systems that do not have use_clockid

---

include/lo2s/perf/syscall/reader.hpp
include/lo2s/perf/tracepoint/reader.hpp

Totally sane behaviour for a code formatting tool to have breaking changes every single version.

fix(formatting): Update formatting to clang 15

---

README.md

This commit brings the README in line with the recent removal of support for systems without clockid or context switch records.
This bumps up the minimum requirement for Linux to 4.3, although both clockid and context switch records appear to be frequently backported features.
Both --help and the manpage did not need adjustements.
This fixes #246

fix(readme): Bring README in line with legacy support removal

---

README.md
man/lo2s.1.pod
src/config.cpp

I think this is the recommended way to get tracepoints access in lo2s.
This fixes #238

feat(tracepoints): Print Help Message if no tracepoints are available

---

include/lo2s/perf/event_provider.hpp
src/perf/event_provider.cpp

Recent GCC versions complain about a possible dangling reference to a temporary.
Fix this warning by returning a copy of the EventDescription instead, as all code paths copy the EventDescription in the end anyways.
This fixes #281.

fix(warning): Fix dangling reference  to temporary warning

---

include/lo2s/perf/bio/reader.hpp
include/lo2s/perf/bio/writer.hpp
src/perf/multi_reader.cpp

nr_sector and sector were switched
in the code path where we need to drop an I/O event if it arrived late, the I/O event was never dropped, resulting in an infinite loop.
This does _not_ fix NVMe support as the cause for that issue is unrelated to our handling of block I/O events.
This fixes #288

fix(block-io): Fix block I/O support

---

src/perf/counter/userspace/writer.cpp

Index 0 in the counter_collection is reserved for the metric leader. However userspace metrics dont have a metric leader, so we have to start counting the events from 1 instead of 0.

Fix off-by-one in userspace metric writer

---

CMakeLists.txt
cmake/FindVeosinfo.cmake
include/lo2s/config.hpp
include/lo2s/monitor/main_monitor.hpp
include/lo2s/monitor/nec_monitor_main.hpp
include/lo2s/monitor/nec_thread_monitor.hpp
include/lo2s/monitor/threaded_monitor.hpp
include/lo2s/topology.hpp
include/lo2s/trace/reg_keys.hpp
include/lo2s/trace/trace.hpp
include/lo2s/types.hpp
include/lo2s/util.hpp
src/config.cpp
src/monitor/main_monitor.cpp
src/monitor/nec_monitor_main.cpp
src/monitor/nec_thread_monitor.cpp
src/trace/trace.cpp
src/util.cpp

This PR implements sampling for NEC Vector accelerators, such as the NEC SX-Aurora Tsubasa cards.
The "--nec" enables NEC sampling. This records the activity of every thread on every card, regardles of the overall sampling mode.
"--nec-readout-interval" controls the interval of the readouts
This fixes #253

feat(sampling): Implement sampling for NEC vector accelerators

---

include/lo2s/util.hpp
src/main.cpp
src/monitor/process_monitor_main.cpp
src/util.cpp

The default soft limit for the number of open file descriptors per-process in most Linux systems is 1024. This results in crashes on most HPC systems I've used recently as even simple lo2s invocations will exceed this limit with all the per-core perf_event_open calls.
This microscopic soft limit is in place because select() only allows fd's < 1024. If you do not plan to use select() in your code, it is safe to bump the file descriptor limit from the soft limit to the hard limit.
We need to save and restore the old limit before we start the program under measurement however, as the resource limits are inherited by forked processes and we can not guarantee that the program under measurement does not do stupid stuff with select()

Bump file descriptor rlimit to hard rlimit by default

---

src/perf/sample/writer.cpp
src/perf/syscall/sample/writer.cpp

For not scheduled threads/processes, the CPU should show -1, but due to implicit casting to unsigned, it used UINT_MAX instead.
Fixes #324

fix: CPU metric has value wrong value

---

src/monitor/process_monitor.cpp

If currently a process exits after ptrace catched it but before sampling with perf_event_open has been set up, perf_event_open will throw ESRCH ("no such process"), aborting lo2s.
Instead, handle ESRCH more gracefully by printing a warning but otherwise ignoring the non-existent process.

fix(process monitoring): dont abort lo2s on unexpected child process exit

---

include/lo2s/pipe.hpp

More modern compilers complain about fds_ and fd_open_ being uninitialized, so initialize them

Initialize arrays in lo2s::Pipe

---

include/lo2s/perf/bio/writer.hpp
include/lo2s/perf/multi_reader.hpp

Due to a bug, when the multi-reader switches from one reader with later events to one that has earlier events, a block I/O event was discarded from the reader with the later events. This predictably led to event loss.
Further, the insert event was switched from block_rq_insert to block_bio_queue. The reason for this is that block_rq_insert never matched the amount of data reported by block_rq_issue and block_rq_complete. I could not find another block_rq_* tracepoint that accounts for the block I/O request that do not enter through block_rq_insert. However, block_bio_queue matches the amount of data that block_rq_issue and block_rq_complete report.
This results in somewhat of a mismatch, as block_bio_* is one level higher up than block_rq_*. This is most notable in that one …

Fix --block-io

---

src/perf/event_provider.cpp

parse the cpumask file for PMUs. For uncore PMUs this contains the core ids the uncore PMUs are logically mapped to (because uncore events naturally do not belong to any core, but we still need some cpuid to be able to perf_event_open them)

Parse cpumask for uncore PMUs

---

include/lo2s/config.hpp
man/lo2s.1.pod
src/config.cpp
src/monitor/process_monitor_main.cpp

Implemented a way for lo2s to detect a call with sudo and then drop its privileges before launching any process. Different methods of gaining root aren't taken into account (yet).
This refers to #301 
To Do:

Drop root privileges before forking

---

include/lo2s/measurement_scope.hpp
include/lo2s/monitor/nec_thread_monitor.hpp
include/lo2s/trace/reg_keys.hpp
include/lo2s/trace/trace.hpp
src/monitor/nec_thread_monitor.cpp

Besides sampling, there are several performance monitor counters that we can read from NEC SX-Aurora accelerators, such as L1 cache misses.
This closes #237 as sampling and PMCs are probably the two reasonable things we can read from lo2s.

Add support for NEC SX-Aurora performance monitor counters

---

CMakeLists.txt
cmake/FindLibpfm.cmake
include/lo2s/perf/event_provider.hpp
include/lo2s/perf/pfm.hpp
src/config.cpp
src/perf/event_provider.cpp

libpfm4 contains information about hundreds of events for dozens of architectures. With this, a user interested in the count of retired instructions on, for example, A64Fx can now use the name "INST_RETIRED".
There are some beauty issues we have to discuss here:
libpfms event name format is hierarchical: `pmu::event:[sub event]`. in `--list-events` I currently just flatten this hierarchy:
```
amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS:ADD_SUB_FLOPS
amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS:ANY
amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS:DIV_FLOPS
amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS:MAC_FLOPS
amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS:MULT_FLOPS
```
but maybe we want
```
amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS
- ADD_SUB_FLOPS
- ANY
- DIV_FLOPS
- MAC_FLOPS
- MULT_FLOPS
```
or even
``` …
```

Add support for parsing event names with libpfm4

---

man/lo2s.1.pod
src/perf/counter/group/reader.cpp

Since the "failed to add counter ..." error seems to be the one occurring if -E does not work, I decided to add a hint to --userspace-metric-event there.
This solves #311

Point to --userspace-metric-event

---

include/lo2s/perf/event_reader.hpp
include/lo2s/shared_memory.hpp

In preperation for CUPTI support, this commit adds a SharedMemory class that wraps Mmap and converts the EventReader to use it.

feat: Add C++ Mmap Wrapper

---

cmake/FindSensors.cmake

Piggy-backing off of binutils is a nice hack, but that is probably not how you are supposed to do this.

fix(cmake): Fix Sensors library inclusion

---

CMakeLists.txt
include/lo2s/build_config.hpp.in
include/lo2s/config.hpp
include/lo2s/cupti/events.hpp
include/lo2s/cupti/reader.hpp
include/lo2s/measurement_scope.hpp
include/lo2s/monitor/process_monitor.hpp
include/lo2s/monitor/scope_monitor.hpp
include/lo2s/monitor/system_process_monitor.hpp
include/lo2s/ringbuf.hpp
include/lo2s/shared_memory.hpp
include/lo2s/trace/reg_keys.hpp
include/lo2s/trace/trace.hpp
include/lo2s/util.hpp
man/lo2s.1.pod
src/config.cpp
src/cupti/lib.cpp
src/monitor/poll_monitor.cpp
src/monitor/process_monitor.cpp
src/monitor/process_monitor_main.cpp
src/monitor/scope_monitor.cpp
src/monitor/system_process_monitor.cpp
src/perf/counter/userspace/reader.cpp
src/trace/trace.cpp
src/util.cpp

This commit adds a --nvidia option, which injects a library into the program under measurement, which records entry and exit into CUDA kernels via CUPTI
We might think about bumping the CMake requirement to 3.24 with this version, as older FindCUDAToolkit.cmake fail to correctly detect CUPTI headers[1].
This implements #294
[1]  https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7608

feat(nvidia): Add cupti support

---

include/lo2s/mmap.hpp
src/mmap.cpp

lo2s is currently not able to resolve the symbols from instruction pointers coming from the kernel.
I have implemented in this PR support for parsing kallsyms to alleviate this.
/proc/kallsyms is a file which records the addresses of symbols inside the running kernel.
One issue is that it only reports the location, not the size of symbols. I simply assume that a symbol ends at the start of the next symbol and the last symbol in the kernel ending at the highest address.
This is how it looks in Vampir currently (callstack view):

feat(symbol resolution): implement kallsyms support

---

include/lo2s/topology.hpp
src/monitor/nec_monitor_main.cpp

ve_check_pid() only works for processes, not threads, so lo2s complained that it could not find the real NEC device id for those threads.
Rewrite the code to use ve_sysfs_path_info(). This gives us the correct sysfs path for a NEC device id, so we dont have to find it using ve_check_pid().

Fix NEC sampling if threads are involved

---

include/lo2s/perf/event.hpp
include/lo2s/perf/pfm.hpp

Fix PFM build/fix warning about uninitialized use

---

.github/workflows/cmake.yml
CMakeLists.txt

This pr adds libpfm4, radare2, libaudit and CUPTI to the CI build.
With this, all optional lo2s dependencies besides:
- veosinfo (No installable build for Ubuntu 20.04 available)
- x86_adapt/x86_energy (Broken even in the https://github.com/s9105947/x86_adapt/tree/fix-linux-5.18 branch)
get build.
One remaining issue is that Ubuntu ships the ancient CUDA 10, resulting in CUPTI support failing to build. Should I patch lo2s to work with CUDA 10, find a way to install a newer CUDA version in the CI, or remove it from the CI?

Add CUPTI. libpfm4, radare2 and libaudit to CI build

---

CMakeLists.txt
cmake/FindAudit.cmake
cmake/FindRadare.cmake
cmake/FindVeosinfo.cmake
cmake/test_static_radare.c

Some libraries were not correctly (or at all) checking for static variants if lo2s_USE_STATIC_LIBS was requested, so I fixed that.

fix(cmake): Fix static build

---

include/lo2s/perf/event.hpp
src/perf/event.cpp
src/perf/event_provider.cpp

Add a function for printing the perf_event_attr of Event's. This is
incredibly useful for debugging.
Printing out the perf_event_attr is triggered on event open and is only
printed when the log level trace is specified
Move pre-defined event table from global to function scope, so that the
events in  it do not get initialized before we set up logging.

Add print_attr()

---

include/lo2s/config.hpp
include/lo2s/perf/counter/metric_writer.hpp
man/lo2s.1.pod
src/config.cpp
src/monitor/cpu_set_monitor.cpp
src/monitor/scope_monitor.cpp
src/perf/event_composer.cpp
src/trace/trace.cpp

This should reduce the overhead in situations where you really only want to track metrics in system-wide mode.

Add the ability to have system-mode without process tracking

---

CMakeLists.txt
cmake/Tests.cmake
cmake/fixtures/paranoid.sh
cmake/fixtures/test_sys_kernel_debug.sh
cmake/tests/block_io/block_io.sh
cmake/tests/process_counters/process_counters.sh
cmake/tests/process_sampling/process_sampling.sh
cmake/tests/sensors_recording/sensors_recording.sh
cmake/tests/syscall_recording/syscall_recording.sh
cmake/tests/system_counters/system_counters.sh
cmake/tests/system_sampling/system_sampling.sh
cmake/tests/tracepoint_recording/tracepoint_recording.sh
include/lo2s/perf/tracepoint/reader.hpp
src/metric/sensors/recorder.cpp
src/perf/event_composer.cpp

This is a proposal for a first simple test, testing if sampling works.
Sadly, I think I can throw the GitHub Action Idea into the bin because PMUs are not passed to the VM, and working around that (by only testing perf software events) seems to be like inviting a whole lot of weirdness into the test process that is not worth the hassle.

Add first simple test

---

CMakeLists.txt
cmake/FindLibDw.cmake

The current cmake logic can be a little bit confusing, because libelf will be reported missing
if libdw can not be found.
So give libdw its own cmake code.

fix(cmake): Split FindLibDw from FindLibElf

---

include/lo2s/trace/trace.hpp
include/lo2s/util.hpp
src/trace/trace.cpp
src/util.cpp

Put all kernel threads in the same regions group based on whether /proc/[pid]/cmdline is empty (this is also how ps checks if something is a kernel thread).
This makes it easier to distinguish kernel threads from normal threads in visualization utilites such as Vampir.

feat (sampling): Put kernel threads in own group.

---

include/lo2s/config.hpp
include/lo2s/function_resolver.hpp
include/lo2s/memory_map.hpp
include/lo2s/resolvers.hpp
src/config.cpp
src/function_resolver.cpp
src/monitor/cpu_set_monitor.cpp
src/monitor/process_monitor_main.cpp
src/perf/sample/writer.cpp
src/trace/trace.cpp

... which for now is mainly targeted at Python. In general though, every JIT compiler is free to generate a perf.map file.
Python, if enabled through the PYTHONPERFSUPPORT env variable or the -X perf command line can now help with generating meaningful traces of Python applications [1].
This works through two parts:
1. The JIT/Interpreter generates a perf.map file at /tmp/perf-{pid}.map, this contains a listing of the location, names and sizes of the JIT symbols. Example content: 
```
deadbeef b my_function 
```
2. In the Python case, because it is not truly a JIT compiler, Python generates little assembler trampolines for every python function. Whenever it starts evaluating a Python function, it goes through this trampoline, so that if the address of the trampoline (in the example above …

feat(sampling): Add perf.map support for JIT compilers/interpreters that support it

---

CMakeLists.txt
include/lo2s/calling_context.hpp
include/lo2s/config.hpp
include/lo2s/local_cctx_tree.hpp
include/lo2s/measurement_scope.hpp
include/lo2s/monitor/openmp_monitor.hpp
include/lo2s/ompt/events.hpp
include/lo2s/ompt/ringbuf.hpp
include/lo2s/trace/trace.hpp
src/config.cpp
src/monitor/openmp_monitor.cpp
src/monitor/process_monitor_main.cpp
src/monitor/socket_monitor.cpp
src/ompt/lib.cpp
src/process_controller.cpp
src/trace/trace.cpp

The content of this commit produces traces of OpenMP program activity which can already capture quite some information about OpenMP programs, but at no point claim to be correct or complete or anything.
On the technical side, the functionality here is based on the ringbuf interface, attaching lo2s to the relevant OMPT callbacks.

Preliminary support for OpenMP recording through OMPT

---

CMakeLists.txt
include/lo2s/calling_context.hpp
include/lo2s/config.hpp
include/lo2s/gpu/events.hpp
include/lo2s/gpu/ringbuf.hpp
include/lo2s/measurement_scope.hpp
include/lo2s/monitor/fwd.hpp
include/lo2s/monitor/gpu_monitor.hpp
include/lo2s/monitor/socket_monitor.hpp
include/lo2s/resolvers.hpp
include/lo2s/ringbuf.hpp
include/lo2s/trace/trace.hpp
include/lo2s/types.hpp
src/config.cpp
src/cuda/lib.cpp
src/hip/lib.cpp
src/monitor/gpu_monitor.cpp
src/monitor/process_monitor_main.cpp
src/monitor/socket_monitor.cpp
src/ompt/lib.cpp
src/trace/trace.cpp

This commit introduces AMD HIP kernel event recording based on the rocprofiler-sdk.
This largely follows the NVidia CUDA kernel event recording we already have, although the AMD API is less sophisticated in some degrees:
- Events do not necessarily arrive ordered. Reorder using a limited size priority_queue, throw away events that have arrived after later ones have already been written.
- There is no way to set an external timestamp source and the internally used clock source, BOOTTIME has issues with being used with perf. Rectify this with a crude time synchronization mechanism.
Additionally move all the CUDA recording code that is used in the AMD code path into a GPU namespace.
This closes #371

feat(gpu): Implement AMD HIP kernel recording

---

cmake/FindLibBpf.cmake
cmake/FindLibDw.cmake

Link libbpf to libdw instead of manually finding and including it.
Edit libbpf find_library calls to make them behave more like every other find_library call in lo2s.
Use library path output by pkg-config as a hint to find_library.

fix(build_system): depend libbpf on libdw, use more standardized find_library calls
