include/lo2s/trace/trace.hpp, include/lo2s/util.hpp, src/trace/trace.cpp, src/util.cpp
Idk, squash merge and pick message of 426731c in merge commit? This should sum up the WIPs before that quite well.
=> Issue #56:  Add uname(2) information to trace file

CMakeLists.txt
No Doxygen config needed apparently, as cmake can generate one
=> Functionality for generating graphs of the code with make doc

src/config.cpp, src/perf/event_provider.cpp
=> raw events

.travis.yml
=> Travis build improvements

src/perf/sample/writer.cpp
For each thread location, thread begin events were written lazily in
conjunction with the first recorded  sample.  If there weren't any
samples recorded for this location, the sample writer would 'forget'
to write the thread begin events.
Now, the sample writer will detect a missing thread begin event before
writing the corresponding thread end event, and write the former with
the earliest timestamp available.
=> Fix sample writer missing thread begin events

include/lo2s/bfd_resolve.hpp, src/bfd_resolve.cpp
What the title says, I hope this is good, as I'm not that familiar with modern C++
Fixes #115
=> Add unique_ptr wrappers for C pointers that need to be freed in bfd_resolve

include/lo2s/config.hpp, include/lo2s/monitor/poll_monitor.hpp, man/lo2s.1.pod, src/config.cpp, src/metric/x86_adapt/monitor.cpp, src/metric/x86_adapt/node_monitor.cpp, src/metric/x86_energy/monitor.cpp, src/monitor/cpu_monitor.cpp, src/monitor/poll_monitor.cpp, src/monitor/thread_monitor.cpp, src/monitor/tracepoint_monitor.cpp
0 means interval based recording is disabled
Fixes #127
=> Add --perf-readout-interval option

.travis.yml, CMakeLists.txt, README.md, cmake/FindStdFilesystem.cmake, include/lo2s/bfd_resolve.hpp, include/lo2s/line_info.hpp, include/lo2s/perf/tracepoint/format.hpp, include/lo2s/perf/tracepoint/reader.hpp, include/lo2s/topology.hpp, include/lo2s/util.hpp, src/bfd_resolve.cpp, src/mmap.cpp, src/monitor/cpu_set_monitor.cpp, src/perf/event_provider.cpp, src/perf/tracepoint/format.cpp, src/summary.cpp, src/topology.cpp, src/trace/trace.cpp, src/util.cpp
Now with 100% less experimental/filesystem hackery :)
=> Replace boost::filesystem with std::filesystem

include/lo2s/monitor/dummy_monitor.hpp, include/lo2s/monitor/poll_monitor.hpp, include/lo2s/perf/event_reader.hpp, include/lo2s/perf/tracepoint/reader.hpp, include/lo2s/radare.hpp, src/metric/x86_adapt/monitor.cpp, src/metric/x86_adapt/node_monitor.cpp, src/metric/x86_energy/monitor.cpp, src/mmap.cpp, src/monitor/poll_monitor.cpp, src/pipe.cpp, src/topology.cpp
While i still think about some stuff, here are some simple changes to use [[maybe_unused]] and std::byte where applicable.
=> C++17ify lo2s

src/trace/trace.cpp
=> Unbreak tracepoints by readding missing check for existence

man/lo2s.1.pod
Does anything need to be considered when updating the manpage?
=> Update lo2s.1.pod / Clarify configuration of plugins.

src/trace/trace.cpp
=> fix(trace): Add sample region to regions_group if regions_group already exists

.github/workflows/cmake.yml, CMakeLists.txt, include/lo2s/monitor/scope_monitor.hpp, include/lo2s/types.hpp, src/monitor/scope_monitor.cpp, src/perf/time/reader.cpp, src/perf/tracepoint/switch_writer.cpp
- Fixes existing build problems for some of the more obscure features
- Also adds a feature summary to the configure step
=> Improved build options selection in CI

.github/workflows/cmake.yml, CMakeLists.txt, README.md, cmake/FindSensors.cmake, include/lo2s/config.hpp, include/lo2s/metric/plugin/wrapper.hpp, include/lo2s/metric/sensors/recorder.hpp, include/lo2s/monitor/main_monitor.hpp, include/lo2s/util.hpp, man/lo2s.1.pod, src/config.cpp, src/metric/plugin/plugin.cpp, src/metric/sensors/recorder.cpp, src/monitor/main_monitor.cpp
Adds the new parameter `-S` that enables the recording of all sensors available through libsensors (lm-sensors)
=> Adds support for libsensors metrics

src/monitor/poll_monitor.cpp
=> fix(PollMonitor): Close TimerFd

include/lo2s/monitor/poll_monitor.hpp, src/monitor/poll_monitor.cpp
=> Issue 239 close timerfd

src/perf/event_provider.cpp
As by their nature, there is no information about which CPUs are supported for any given raw event swimming somewhere in the kernel, the only solution to get the set of supported CPUs is good old trial-and-error
=> feat(metrics): Support heterogenous architectures with raw events

CITATION.cff
Note that this has to be updated on every release!
This fixes #263
=> feat(citation): Add CITATION.cff file

include/lo2s/perf/event_reader.hpp
Use __atomic_load_n and __atomic_store_n. those are equivalent to the the smp_load_acquire and smp_store_release functions used in [ring_buffer.h in the linux kernel](https://github.com/torvalds/linux/blob/master/tools/include/linux/ring_buffer.h).
As a proof, they produce the exact same assembly on 
x86: https://godbolt.org/z/s7cMoe5vK
and 
ARM: https://godbolt.org/z/6oYrKnbzv
This fixes #287
=> fix(perf): use correct atomic memory operations

src/monitor/process_monitor_main.cpp, src/util.cpp
Add error checks to fd rlimit bumping code.
=> Add error checks

man/lo2s.1.pod, src/config.cpp, src/monitor/process_monitor_main.cpp
I've implemented the changes that were requested in PR #333. This is a new branch since the original branch is already merged.
=> Edit setuid() options as requested in PR #333

src/trace/trace.cpp
issue 155 highlights some code that makes lo2s crash due to very fast thread enters/exits.
Most of the highlighted issues/warnings have been resolved, however lo2s still crashes on the given code. This is due to missing OTF2 definitions for the process the threads belong to.
In the case that there is no process, emplace a thread as its own process. This is probably breaks some assumptions about processes (I am pretty sure that this makes function resolution for that thread impossible, because we track that on a process basis) in lo2s, but at least it does not crash anymore.
This closes #155
=> fix(sampling): Fix issues with simultaneous thread creation
